#! /usr/bin/python
import os,subprocess,socket

#	The OpenHost Project
#	 daknob@tolabaki.gr

o = subprocess.Popen("who", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
o,e = o.communicate()
u = o.split("\n")
ru = []
for user in u:
	ru.insert(0, user.split(" ")[0])
out = open("/path/to/OpenHost/uid/" + socket.gethostname(), "w+")
out.write(str(len(ru)-1))
out.close()
#Saving users to array because we might need them in the future..
